### ISSUE TITLE
思想挺不错的，需要更多介绍和用法

### ISSUE THREAD

**Issue by RondaHo** [JC-Hu/JHCellConfig#1]
对于一个tableView有多个不同类型的cell，确实非常好控制，添加删除section不需要改动tableView代理方法。需要详细一点的介绍

**Comment by JC-Hu** [comment]
谢谢。你觉得，哪些方面最需要一些详细的讲解？

**Comment by JC-Hu** [comment]
谢谢。   这的确是一个写tableView的新的方式，我在实际开发中，对于不同需求也遇到了些问题，但最后都想到了很好的解决办法，只是时间有限，还没办法全部整理上来。

你觉得，哪些方面最需要更详细的介绍？

**Comment by RondaHe** [comment]
谢谢作者的答复！
可以介绍一下主要思想，然后用一个含有多个section和row的tableView进一步说明用法，光一个demo看起来有时有点不明所以

**Comment by JC-Hu** [comment]
哈，看来你看的不够仔细哦！Demo中，section 0  就是有两个row的！数据源dataArray是二维数组，千万不要忽略这一点。

不过目前的Demo确实比较单薄，有时间我会加入更多，比如数量不确定且高度自适应的cell（如评论列表中的cell）。
