### ISSUE TITLE
是否能夠顯示不固定圖文格式

### ISSUE THREAD

**Issue by xjimi** [JC-Hu/JHCellConfig#2]
是否能夠顯示不固定圖文格式
沒有固定圖片數量的cell

**Comment by JC-Hu** [comment]
我还没有试过这种。但分析一下，跟demo里“高级评论”的原理差不多，只要在cell类里写一个根据数据计算高度的类方法，然后在tableView的返回cell高度的代理方法中，根据cellConfig.title判断出cell类型，再调用计算高度的方法，应该就差不多了吧？还有很多细节上的代码，请看demo里SecondViewController.m
