### ISSUE TITLE
demo 里面没有加载xib cell的介绍   在哪里可以问一下

### ISSUE THREAD

**Issue by zhaomengshan** [JC-Hu/JHCellConfig#3]

**Comment by JC-Hu** [comment]
生成JHCellConfig实例的时候调用-useNib就可以了。如：  
 ` JHCellConfig *cellConfig = [JHCellConfig cellConfigWithCellClass:[ZTProductListTableViewCell class] dataModel:model].useNib;
`

**Comment by zhaomengshan** [comment]
谢谢 ，如果cell的高度是用第三方库的话还能
是不是就不能用了

**Comment by zhaomengshan** [comment]
1927813567   希望加一下QQ详细问一下

**Comment by JC-Hu** [comment]
可以的，在cell.m里实现 + (CGFloat)cellHeightWithCellConfig:(JHCellConfig *)cellConfig ，在这里面计算并返回高度。
如果需要相关的tableView变量可以利用JHCellConfig的tableView属性来传值。
时间有限，相关的实现在Demo里确实没有些，谢谢你指出来，有空我会加以完善

**Comment by zhaomengshan** [comment]
id model = self.modelsArray[indexPath.row];
    // 获取cell高度
    return [self.tableView cellHeightForIndexPath:indexPath model:model keyPath:@"model" cellClass:[DemoVC9Cell class]  contentViewWidth:cellContentViewWith];
--------------------- 
这个本来是写在  VC 里面的但是放到cell里面怎么获取  indexPath 呢

**Comment by JC-Hu** [comment]
我这边还没有遇到cell里需要indexPath的情况，因为cell本身不应该关心自己再什么位置，只应该关心根据数据模型来展示。

而你的具体情况，用的是FDTemplateLayoutCell吧，作者也说了，cell高度计算用indexPath缓存其实不是合理的。我已经给cellConfig增加了自动高度计算的功能，一会儿就会发布。

所以你的解决方案，
1. 用cellConfig.dataModel 来传递业务模型model，用cellConfig新增的高度计算功能计算高度
2.坚持用FDTemplateLayoutCell，可以新建一个CellModel，包含两个属性，indexPath和业务模型model，用cellConfig.dataModel来传递cellModel

**Comment by zhaomengshan** [comment]
我用的是SDAutolayout    https://github.com/gsdios/SDAutoLayout
不知道你有没有了解过  
他计算高度的方法是写在VC里面的但是你所有的布局和计算高度是放在cell里面的 
我不知道怎么变通  有空加一个QQ 你的库可能还需要加一个功能

**Comment by JC-Hu** [comment]
有问题就在issue里讨论吧，这样其他人有同样的问题就可以找到答案了。

如我上个回复所说，你需要变量基本都可以通过这个方法来传递。

如果碰到了问题，请把具体的情况描述清楚，我尽量帮助你解决。

**Comment by zhaomengshan** [comment]
不是的我有其中的属性和细节不是太明白 ，一个一个发太费劲了 ，麻烦加我一下，我的项目用了这个库，进度已经落后了

**Comment by JC-Hu** [comment]
我愿意在一定程度上帮助你，但这归根结底你的事情，你的问题。

你都不愿意费些心思把问题描述清楚，让我更快更准确的了解你的问题，我又为什么要花更多的时间和精力来帮你呢

发自我的 iPhone

**Comment by zhaomengshan** [comment]
我只是觉得GitHub 描述问题不够 及时有效  ，我已经写好了，虽然舍弃你的库 ，但是觉得你的想法还是可以的，抽离的不够彻底 ，适应范围很有限 ，demo 写的不够详细 ，你不愿意的事情我也不会勉强，不过是学习交流而已 ，我不觉得我 没有描述清楚 ，说话不要咄咄逼人 ，iOS的东西很多，路上也不止你一个人

**Comment by JC-Hu** [comment]
嗯，加油。
希望有朝一日你能做的比我好。
做一个抽离的彻底，适应范围很广，demo写的详细的库。
也欢迎直接fork这个库，把它改造的更好。
